model = "gpt-5.2-codex"
model_reasoning_effort = "high"

[projects."/Users/noah/code/openai"]
trust_level = "trusted"

[projects."/Users/noah/.dotfiles"]
trust_level = "trusted"

[projects."/Users/noah/code/git-stack-cli"]
trust_level = "trusted"

[notice]
hide_full_access_warning = true

[notice.model_migrations]
gpt-5-codex = "gpt-5.2-codex"
